export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SERVER_ERROR = 'SERVER_ERROR';

// authentication
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const CONFIRM_SUCCESSFUL = 'CONFIRM_SUCCESSFUL';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const EMAIL_SENT = 'EMAIL_SENT';
